repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        args: ["--ext", ".ts,.tsx"]

  - repo: https://github.com/prettier/prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args: ["--write", "--parser", "typescript"]

  - repo: https://github.com/pre-commit/mirrors-typescipt-eslint
    rev: v6.10.0  # Use the latest TypeScript-ESLint version
    hooks:
      - id: eslint
        args: ["--ext", ".ts,.tsx"]

  - repo: https://github.com/typicode/husky
    rev: v8.0.3
    hooks:
      - id: husky
